### ISSUE TITLE
duplicated option: modules

### ISSUE THREAD

**Issue by elros88** [yokomizor/ejabberd-auth-jwt#10]
Greeting I'm try to install the module in my local environment following the README instructions, but I'm getting this error:
`
15:35:25.116 [info] Loading configuration from /home/antonio/ejabberd-19.08/conf/ejabberd.yml

15:35:25.249 [critical] Failed to start ejabberd application: Configuration error: duplicated option: modules
`
I'm using the Ejabberd version 19.08 on Linux Mint

**Comment by yokomizor** [comment]
Hi @elros88, sorry about the delay :X

Thank you for your feedback. I am just checking ejabberd CHANGELOG and it looks like since 19.08 ejabberd supports JWT authentication. That means that this module is no longer needed.

https://github.com/processone/ejabberd/blob/master/CHANGELOG.md#version-1908
```
New authentication method using JWT tokens
```

**Comment by yokomizor** [comment]
https://github.com/processone/ejabberd/commit/3e5c0a1df84b3e7871178fea350d1c2ec2537c6d
