### ISSUE TITLE
Unknown option 'jwtauth_key'

### ISSUE THREAD

**Issue by binhrobin** [yokomizor/ejabberd-auth-jwt#4]
Hi, After install this module to ejabberd server.
I start and see this log although i added this option in ejabberd.yml

hosts:
  - "meepo.vn"

loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

jwtauth_key: ""
jwtauth_pem_file: ""
jwtauth_user_claim: "sub"
jwtauth_strict_alg: "HS256"

Loading configuration from /Users/lv/ejabberd/etc/ejabberd/ejabberd.yml
18:00:31.419 [error] Unknown option 'jwtauth_key'
18:00:31.419 [error] Failed to load configuration file /Users/lv/ejabberd/etc/ejabberd/ejabberd.yml
18:00:31.419 [critical] Failed to start ejabberd application: unknown_option

**Comment by yokomizor** [comment]
Hi,

Since 18.06, Ejabberd won't start with unknown options: https://blog.process-one.net/ejabberd-18-06/

> Stop ejabberd initialization on invalid/unknown options
Since some time now, we are warning ejabberd admins in log file about incorrect configuration options. We feel that we are ready to make these hints strong requirements about config file validity.
>
> Starting with ejabberd 18.06, ejabberd will not ignore unknown options and doesn’t allow to have options with malformed values. The rationale for this is to avoid unexpected behaviour during runtime, i.e. to conform to “fail early” approach. We thus hope to be helpful to newcomers by making sure they properly format their config files to get the expected behaviour.
>
> Note that it’s safe to reload a configuration with potentially invalid and/or unknown options:
this will not halt ejabberd, but will only prevent the configuration from loading.

Auth modules do not use `gen_mod` behaviour, and for this reason, new ejabberd versions don't know how to configure them. I don't know how to solve this issue yet. I will wait until they fix `ejabberd_auth_http`, then I will use the same strategy.

https://github.com/processone/ejabberd-contrib/issues/262

**Comment by yokomizor** [comment]
I just tested this config using docker:

`docker run -it --rm -p 5280:5280 -p 5222:5222 -v $(pwd):/home/ejabberd/.ejabberd-modules/sources/ejabberd_auth_jwt/ ejabberd/ecs foreground`

Ejabberd starts just fine:

```
...
21:48:04.252 [info] ejabberd 18.6.0 is started in the node ejabberd@eeedde8fa283 in 2.10s
21:48:04.255 [info] Application ejabberd started on node ejabberd@eeedde8fa283
21:48:04.255 [info] Start accepting TCP connections at [::]:5222 for ejabberd_c2s
21:48:04.255 [info] Start accepting TCP connections at [::]:5269 for ejabberd_s2s_in
21:48:04.255 [info] Start accepting TCP connections at [::]:5280 for ejabberd_http
21:48:04.289 [info] Application iex started on node ejabberd@eeedde8fa283
21:48:04.307 [info] Application runtime_tools started on node ejabberd@eeedde8fa283
```

**Comment by yokomizor** [comment]
Changing from `ejabberd_config` to `gen_mod` behaviour seems to fix the problem:

https://github.com/yokomizor/ejabberd-auth-jwt/commit/e80a3ae300a68c4f288685efc60a7864b20d0f32
